# Site settings
title: Under construction
email: tntranloc@gmail.com
url: https://github.com/tntranloc/tntranloc.github.io
description: "My Portfolio"
keywords: "genetics, data science, phd, plants, graphics"
skills: "Plant Biology - Quantitative Genetics - Hobbyist Digital Art/Violinist"
meta_author: Tran  Nhu

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 391d00 #959D90 
  primary-rgb: "57, 29, 0" #"149, 157, 144" 
  secondary: ce9b00 #3C5759 
  secondary-dark: a77e00 #304647 

# Footer settings
footer:
  copyright: Nhu LT Tran
  location: Current location
  social: Find me around the web at
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/nhu-tran-a8751890
  - title: instagram
    url: https://www.instagram.com/locthuynhu
  - title: mastodon
    url: https://mastodon.social/@locthuynhu

    
# Postal address (add as many lines as necessary)
address:
  - line: Biozentrum, University of Cologne
  - line: 50674 Cologne, Germany

# Credits content
credits: 'My thanks to the creator of the <a href="https://jekyllthemes.io/theme/freelancer-theme">Freelancer Jekyll Theme</a> upon which my website design is based. All images and illustrations on this website are my original work. If you like my art, you can check my shop out on <a href="https://www.redbubble.com/people/elichakkari/shop?asc=u">Redbubble Theme</a>'

# Build settings
markdown: kramdown
permalink: pretty
future: true
#timezone: GMT+2 #TZ: Europe/Germany 

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
